version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - http.cors.enabled=true
      - ELASTIC_CONTAINER=true
    networks:
      - of-analytics-net
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.16.1
    environment:
      - ELASTIC_CONTAINER=true
    networks:
      - of-analytics-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  of-analytics-net:
    driver: bridge