name: Check Prettier formatting has been applied

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run prettier
        run: |-
          npx prettier --config .prettierrc --check .
